// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ex.proto
 
package prototest;

public final class Ex {
  private Ex() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HobbyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
  }
  public static final class Hobby extends
      com.google.protobuf.GeneratedMessage
      implements HobbyOrBuilder {
    // Use Hobby.newBuilder() to construct.
    private Hobby(Builder builder) {
      super(builder);
    }
    private Hobby(boolean noInit) {}
    
    private static final Hobby defaultInstance;
    public static Hobby getDefaultInstance() {
      return defaultInstance;
    }
    
    public Hobby getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return prototest.Ex.internal_static_prototest_Hobby_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return prototest.Ex.internal_static_prototest_Hobby_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static prototest.Ex.Hobby parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static prototest.Ex.Hobby parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static prototest.Ex.Hobby parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static prototest.Ex.Hobby parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static prototest.Ex.Hobby parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static prototest.Ex.Hobby parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static prototest.Ex.Hobby parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static prototest.Ex.Hobby parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static prototest.Ex.Hobby parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static prototest.Ex.Hobby parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(prototest.Ex.Hobby prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements prototest.Ex.HobbyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return prototest.Ex.internal_static_prototest_Hobby_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return prototest.Ex.internal_static_prototest_Hobby_fieldAccessorTable;
      }
      
      // Construct using prototest.Ex.Hobby.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return prototest.Ex.Hobby.getDescriptor();
      }
      
      public prototest.Ex.Hobby getDefaultInstanceForType() {
        return prototest.Ex.Hobby.getDefaultInstance();
      }
      
      public prototest.Ex.Hobby build() {
        prototest.Ex.Hobby result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private prototest.Ex.Hobby buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        prototest.Ex.Hobby result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public prototest.Ex.Hobby buildPartial() {
        prototest.Ex.Hobby result = new prototest.Ex.Hobby(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof prototest.Ex.Hobby) {
          return mergeFrom((prototest.Ex.Hobby)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(prototest.Ex.Hobby other) {
        if (other == prototest.Ex.Hobby.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:prototest.Hobby)
    }
    
    static {
      defaultInstance = new Hobby(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:prototest.Hobby)
  }
  
  public interface PersonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // required string name = 2;
    boolean hasName();
    String getName();
    
    // optional string email = 3;
    boolean hasEmail();
    String getEmail();
    
    // optional .prototest.Hobby hobby = 4;
    boolean hasHobby();
    prototest.Ex.Hobby getHobby();
    prototest.Ex.HobbyOrBuilder getHobbyOrBuilder();
  }
  public static final class Person extends
      com.google.protobuf.GeneratedMessage
      implements PersonOrBuilder {
    // Use Person.newBuilder() to construct.
    private Person(Builder builder) {
      super(builder);
    }
    private Person(boolean noInit) {}
    
    private static final Person defaultInstance;
    public static Person getDefaultInstance() {
      return defaultInstance;
    }
    
    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return prototest.Ex.internal_static_prototest_Person_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return prototest.Ex.internal_static_prototest_Person_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string email = 3;
    public static final int EMAIL_FIELD_NUMBER = 3;
    private java.lang.Object email_;
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          email_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional .prototest.Hobby hobby = 4;
    public static final int HOBBY_FIELD_NUMBER = 4;
    private prototest.Ex.Hobby hobby_;
    public boolean hasHobby() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public prototest.Ex.Hobby getHobby() {
      return hobby_;
    }
    public prototest.Ex.HobbyOrBuilder getHobbyOrBuilder() {
      return hobby_;
    }
    
    private void initFields() {
      id_ = 0;
      name_ = "";
      email_ = "";
      hobby_ = prototest.Ex.Hobby.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasHobby()) {
        if (!getHobby().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEmailBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, hobby_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEmailBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, hobby_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static prototest.Ex.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static prototest.Ex.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static prototest.Ex.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static prototest.Ex.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static prototest.Ex.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static prototest.Ex.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static prototest.Ex.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static prototest.Ex.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static prototest.Ex.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static prototest.Ex.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(prototest.Ex.Person prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements prototest.Ex.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return prototest.Ex.internal_static_prototest_Person_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return prototest.Ex.internal_static_prototest_Person_fieldAccessorTable;
      }
      
      // Construct using prototest.Ex.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHobbyFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (hobbyBuilder_ == null) {
          hobby_ = prototest.Ex.Hobby.getDefaultInstance();
        } else {
          hobbyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return prototest.Ex.Person.getDescriptor();
      }
      
      public prototest.Ex.Person getDefaultInstanceForType() {
        return prototest.Ex.Person.getDefaultInstance();
      }
      
      public prototest.Ex.Person build() {
        prototest.Ex.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private prototest.Ex.Person buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        prototest.Ex.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public prototest.Ex.Person buildPartial() {
        prototest.Ex.Person result = new prototest.Ex.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (hobbyBuilder_ == null) {
          result.hobby_ = hobby_;
        } else {
          result.hobby_ = hobbyBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof prototest.Ex.Person) {
          return mergeFrom((prototest.Ex.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(prototest.Ex.Person other) {
        if (other == prototest.Ex.Person.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasEmail()) {
          setEmail(other.getEmail());
        }
        if (other.hasHobby()) {
          mergeHobby(other.getHobby());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (hasHobby()) {
          if (!getHobby().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              email_ = input.readBytes();
              break;
            }
            case 34: {
              prototest.Ex.Hobby.Builder subBuilder = prototest.Ex.Hobby.newBuilder();
              if (hasHobby()) {
                subBuilder.mergeFrom(getHobby());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHobby(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // required string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional string email = 3;
      private java.lang.Object email_ = "";
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEmail(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
        return this;
      }
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      void setEmail(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        email_ = value;
        onChanged();
      }
      
      // optional .prototest.Hobby hobby = 4;
      private prototest.Ex.Hobby hobby_ = prototest.Ex.Hobby.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          prototest.Ex.Hobby, prototest.Ex.Hobby.Builder, prototest.Ex.HobbyOrBuilder> hobbyBuilder_;
      public boolean hasHobby() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public prototest.Ex.Hobby getHobby() {
        if (hobbyBuilder_ == null) {
          return hobby_;
        } else {
          return hobbyBuilder_.getMessage();
        }
      }
      public Builder setHobby(prototest.Ex.Hobby value) {
        if (hobbyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          hobby_ = value;
          onChanged();
        } else {
          hobbyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder setHobby(
          prototest.Ex.Hobby.Builder builderForValue) {
        if (hobbyBuilder_ == null) {
          hobby_ = builderForValue.build();
          onChanged();
        } else {
          hobbyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder mergeHobby(prototest.Ex.Hobby value) {
        if (hobbyBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              hobby_ != prototest.Ex.Hobby.getDefaultInstance()) {
            hobby_ =
              prototest.Ex.Hobby.newBuilder(hobby_).mergeFrom(value).buildPartial();
          } else {
            hobby_ = value;
          }
          onChanged();
        } else {
          hobbyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      public Builder clearHobby() {
        if (hobbyBuilder_ == null) {
          hobby_ = prototest.Ex.Hobby.getDefaultInstance();
          onChanged();
        } else {
          hobbyBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      public prototest.Ex.Hobby.Builder getHobbyBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getHobbyFieldBuilder().getBuilder();
      }
      public prototest.Ex.HobbyOrBuilder getHobbyOrBuilder() {
        if (hobbyBuilder_ != null) {
          return hobbyBuilder_.getMessageOrBuilder();
        } else {
          return hobby_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          prototest.Ex.Hobby, prototest.Ex.Hobby.Builder, prototest.Ex.HobbyOrBuilder> 
          getHobbyFieldBuilder() {
        if (hobbyBuilder_ == null) {
          hobbyBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              prototest.Ex.Hobby, prototest.Ex.Hobby.Builder, prototest.Ex.HobbyOrBuilder>(
                  hobby_,
                  getParentForChildren(),
                  isClean());
          hobby_ = null;
        }
        return hobbyBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:prototest.Person)
    }
    
    static {
      defaultInstance = new Person(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:prototest.Person)
  }
  
  public interface AddressBookOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .prototest.Person person = 1;
    java.util.List<prototest.Ex.Person> 
        getPersonList();
    prototest.Ex.Person getPerson(int index);
    int getPersonCount();
    java.util.List<? extends prototest.Ex.PersonOrBuilder> 
        getPersonOrBuilderList();
    prototest.Ex.PersonOrBuilder getPersonOrBuilder(
        int index);
  }
  public static final class AddressBook extends
      com.google.protobuf.GeneratedMessage
      implements AddressBookOrBuilder {
    // Use AddressBook.newBuilder() to construct.
    private AddressBook(Builder builder) {
      super(builder);
    }
    private AddressBook(boolean noInit) {}
    
    private static final AddressBook defaultInstance;
    public static AddressBook getDefaultInstance() {
      return defaultInstance;
    }
    
    public AddressBook getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return prototest.Ex.internal_static_prototest_AddressBook_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return prototest.Ex.internal_static_prototest_AddressBook_fieldAccessorTable;
    }
    
    // repeated .prototest.Person person = 1;
    public static final int PERSON_FIELD_NUMBER = 1;
    private java.util.List<prototest.Ex.Person> person_;
    public java.util.List<prototest.Ex.Person> getPersonList() {
      return person_;
    }
    public java.util.List<? extends prototest.Ex.PersonOrBuilder> 
        getPersonOrBuilderList() {
      return person_;
    }
    public int getPersonCount() {
      return person_.size();
    }
    public prototest.Ex.Person getPerson(int index) {
      return person_.get(index);
    }
    public prototest.Ex.PersonOrBuilder getPersonOrBuilder(
        int index) {
      return person_.get(index);
    }
    
    private void initFields() {
      person_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getPersonCount(); i++) {
        if (!getPerson(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < person_.size(); i++) {
        output.writeMessage(1, person_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < person_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, person_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static prototest.Ex.AddressBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static prototest.Ex.AddressBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static prototest.Ex.AddressBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static prototest.Ex.AddressBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static prototest.Ex.AddressBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static prototest.Ex.AddressBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static prototest.Ex.AddressBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static prototest.Ex.AddressBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static prototest.Ex.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static prototest.Ex.AddressBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(prototest.Ex.AddressBook prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements prototest.Ex.AddressBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return prototest.Ex.internal_static_prototest_AddressBook_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return prototest.Ex.internal_static_prototest_AddressBook_fieldAccessorTable;
      }
      
      // Construct using prototest.Ex.AddressBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          personBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return prototest.Ex.AddressBook.getDescriptor();
      }
      
      public prototest.Ex.AddressBook getDefaultInstanceForType() {
        return prototest.Ex.AddressBook.getDefaultInstance();
      }
      
      public prototest.Ex.AddressBook build() {
        prototest.Ex.AddressBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private prototest.Ex.AddressBook buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        prototest.Ex.AddressBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public prototest.Ex.AddressBook buildPartial() {
        prototest.Ex.AddressBook result = new prototest.Ex.AddressBook(this);
        int from_bitField0_ = bitField0_;
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            person_ = java.util.Collections.unmodifiableList(person_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof prototest.Ex.AddressBook) {
          return mergeFrom((prototest.Ex.AddressBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(prototest.Ex.AddressBook other) {
        if (other == prototest.Ex.AddressBook.getDefaultInstance()) return this;
        if (personBuilder_ == null) {
          if (!other.person_.isEmpty()) {
            if (person_.isEmpty()) {
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePersonIsMutable();
              person_.addAll(other.person_);
            }
            onChanged();
          }
        } else {
          if (!other.person_.isEmpty()) {
            if (personBuilder_.isEmpty()) {
              personBuilder_.dispose();
              personBuilder_ = null;
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
              personBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPersonFieldBuilder() : null;
            } else {
              personBuilder_.addAllMessages(other.person_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getPersonCount(); i++) {
          if (!getPerson(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              prototest.Ex.Person.Builder subBuilder = prototest.Ex.Person.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPerson(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .prototest.Person person = 1;
      private java.util.List<prototest.Ex.Person> person_ =
        java.util.Collections.emptyList();
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = new java.util.ArrayList<prototest.Ex.Person>(person_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          prototest.Ex.Person, prototest.Ex.Person.Builder, prototest.Ex.PersonOrBuilder> personBuilder_;
      
      public java.util.List<prototest.Ex.Person> getPersonList() {
        if (personBuilder_ == null) {
          return java.util.Collections.unmodifiableList(person_);
        } else {
          return personBuilder_.getMessageList();
        }
      }
      public int getPersonCount() {
        if (personBuilder_ == null) {
          return person_.size();
        } else {
          return personBuilder_.getCount();
        }
      }
      public prototest.Ex.Person getPerson(int index) {
        if (personBuilder_ == null) {
          return person_.get(index);
        } else {
          return personBuilder_.getMessage(index);
        }
      }
      public Builder setPerson(
          int index, prototest.Ex.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.set(index, value);
          onChanged();
        } else {
          personBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPerson(
          int index, prototest.Ex.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.set(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPerson(prototest.Ex.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(value);
          onChanged();
        } else {
          personBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPerson(
          int index, prototest.Ex.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(index, value);
          onChanged();
        } else {
          personBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPerson(
          prototest.Ex.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPerson(
          int index, prototest.Ex.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPerson(
          java.lang.Iterable<? extends prototest.Ex.Person> values) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          super.addAll(values, person_);
          onChanged();
        } else {
          personBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          personBuilder_.clear();
        }
        return this;
      }
      public Builder removePerson(int index) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.remove(index);
          onChanged();
        } else {
          personBuilder_.remove(index);
        }
        return this;
      }
      public prototest.Ex.Person.Builder getPersonBuilder(
          int index) {
        return getPersonFieldBuilder().getBuilder(index);
      }
      public prototest.Ex.PersonOrBuilder getPersonOrBuilder(
          int index) {
        if (personBuilder_ == null) {
          return person_.get(index);  } else {
          return personBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends prototest.Ex.PersonOrBuilder> 
           getPersonOrBuilderList() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(person_);
        }
      }
      public prototest.Ex.Person.Builder addPersonBuilder() {
        return getPersonFieldBuilder().addBuilder(
            prototest.Ex.Person.getDefaultInstance());
      }
      public prototest.Ex.Person.Builder addPersonBuilder(
          int index) {
        return getPersonFieldBuilder().addBuilder(
            index, prototest.Ex.Person.getDefaultInstance());
      }
      public java.util.List<prototest.Ex.Person.Builder> 
           getPersonBuilderList() {
        return getPersonFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          prototest.Ex.Person, prototest.Ex.Person.Builder, prototest.Ex.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              prototest.Ex.Person, prototest.Ex.Person.Builder, prototest.Ex.PersonOrBuilder>(
                  person_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:prototest.AddressBook)
    }
    
    static {
      defaultInstance = new AddressBook(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:prototest.AddressBook)
  }
  
  public interface AThingOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string toys = 1;
    java.util.List<String> getToysList();
    int getToysCount();
    String getToys(int index);
    
    // repeated int32 luckynumbers = 2;
    java.util.List<java.lang.Integer> getLuckynumbersList();
    int getLuckynumbersCount();
    int getLuckynumbers(int index);
  }
  public static final class AThing extends
      com.google.protobuf.GeneratedMessage
      implements AThingOrBuilder {
    // Use AThing.newBuilder() to construct.
    private AThing(Builder builder) {
      super(builder);
    }
    private AThing(boolean noInit) {}
    
    private static final AThing defaultInstance;
    public static AThing getDefaultInstance() {
      return defaultInstance;
    }
    
    public AThing getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return prototest.Ex.internal_static_prototest_AThing_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return prototest.Ex.internal_static_prototest_AThing_fieldAccessorTable;
    }
    
    // repeated string toys = 1;
    public static final int TOYS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList toys_;
    public java.util.List<String>
        getToysList() {
      return toys_;
    }
    public int getToysCount() {
      return toys_.size();
    }
    public String getToys(int index) {
      return toys_.get(index);
    }
    
    // repeated int32 luckynumbers = 2;
    public static final int LUCKYNUMBERS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> luckynumbers_;
    public java.util.List<java.lang.Integer>
        getLuckynumbersList() {
      return luckynumbers_;
    }
    public int getLuckynumbersCount() {
      return luckynumbers_.size();
    }
    public int getLuckynumbers(int index) {
      return luckynumbers_.get(index);
    }
    
    private void initFields() {
      toys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      luckynumbers_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < toys_.size(); i++) {
        output.writeBytes(1, toys_.getByteString(i));
      }
      for (int i = 0; i < luckynumbers_.size(); i++) {
        output.writeInt32(2, luckynumbers_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < toys_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(toys_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getToysList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < luckynumbers_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(luckynumbers_.get(i));
        }
        size += dataSize;
        size += 1 * getLuckynumbersList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static prototest.Ex.AThing parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static prototest.Ex.AThing parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static prototest.Ex.AThing parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static prototest.Ex.AThing parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static prototest.Ex.AThing parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static prototest.Ex.AThing parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static prototest.Ex.AThing parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static prototest.Ex.AThing parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static prototest.Ex.AThing parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static prototest.Ex.AThing parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(prototest.Ex.AThing prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements prototest.Ex.AThingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return prototest.Ex.internal_static_prototest_AThing_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return prototest.Ex.internal_static_prototest_AThing_fieldAccessorTable;
      }
      
      // Construct using prototest.Ex.AThing.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        toys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        luckynumbers_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return prototest.Ex.AThing.getDescriptor();
      }
      
      public prototest.Ex.AThing getDefaultInstanceForType() {
        return prototest.Ex.AThing.getDefaultInstance();
      }
      
      public prototest.Ex.AThing build() {
        prototest.Ex.AThing result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private prototest.Ex.AThing buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        prototest.Ex.AThing result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public prototest.Ex.AThing buildPartial() {
        prototest.Ex.AThing result = new prototest.Ex.AThing(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          toys_ = new com.google.protobuf.UnmodifiableLazyStringList(
              toys_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.toys_ = toys_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          luckynumbers_ = java.util.Collections.unmodifiableList(luckynumbers_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.luckynumbers_ = luckynumbers_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof prototest.Ex.AThing) {
          return mergeFrom((prototest.Ex.AThing)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(prototest.Ex.AThing other) {
        if (other == prototest.Ex.AThing.getDefaultInstance()) return this;
        if (!other.toys_.isEmpty()) {
          if (toys_.isEmpty()) {
            toys_ = other.toys_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureToysIsMutable();
            toys_.addAll(other.toys_);
          }
          onChanged();
        }
        if (!other.luckynumbers_.isEmpty()) {
          if (luckynumbers_.isEmpty()) {
            luckynumbers_ = other.luckynumbers_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureLuckynumbersIsMutable();
            luckynumbers_.addAll(other.luckynumbers_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureToysIsMutable();
              toys_.add(input.readBytes());
              break;
            }
            case 16: {
              ensureLuckynumbersIsMutable();
              luckynumbers_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addLuckynumbers(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string toys = 1;
      private com.google.protobuf.LazyStringList toys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureToysIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          toys_ = new com.google.protobuf.LazyStringArrayList(toys_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getToysList() {
        return java.util.Collections.unmodifiableList(toys_);
      }
      public int getToysCount() {
        return toys_.size();
      }
      public String getToys(int index) {
        return toys_.get(index);
      }
      public Builder setToys(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureToysIsMutable();
        toys_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addToys(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureToysIsMutable();
        toys_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllToys(
          java.lang.Iterable<String> values) {
        ensureToysIsMutable();
        super.addAll(values, toys_);
        onChanged();
        return this;
      }
      public Builder clearToys() {
        toys_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addToys(com.google.protobuf.ByteString value) {
        ensureToysIsMutable();
        toys_.add(value);
        onChanged();
      }
      
      // repeated int32 luckynumbers = 2;
      private java.util.List<java.lang.Integer> luckynumbers_ = java.util.Collections.emptyList();;
      private void ensureLuckynumbersIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          luckynumbers_ = new java.util.ArrayList<java.lang.Integer>(luckynumbers_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<java.lang.Integer>
          getLuckynumbersList() {
        return java.util.Collections.unmodifiableList(luckynumbers_);
      }
      public int getLuckynumbersCount() {
        return luckynumbers_.size();
      }
      public int getLuckynumbers(int index) {
        return luckynumbers_.get(index);
      }
      public Builder setLuckynumbers(
          int index, int value) {
        ensureLuckynumbersIsMutable();
        luckynumbers_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addLuckynumbers(int value) {
        ensureLuckynumbersIsMutable();
        luckynumbers_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllLuckynumbers(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureLuckynumbersIsMutable();
        super.addAll(values, luckynumbers_);
        onChanged();
        return this;
      }
      public Builder clearLuckynumbers() {
        luckynumbers_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:prototest.AThing)
    }
    
    static {
      defaultInstance = new AThing(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:prototest.AThing)
  }
  
  public interface AListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated int32 age = 1;
    java.util.List<java.lang.Integer> getAgeList();
    int getAgeCount();
    int getAge(int index);
    
    // repeated .prototest.AThing things = 2;
    java.util.List<prototest.Ex.AThing> 
        getThingsList();
    prototest.Ex.AThing getThings(int index);
    int getThingsCount();
    java.util.List<? extends prototest.Ex.AThingOrBuilder> 
        getThingsOrBuilderList();
    prototest.Ex.AThingOrBuilder getThingsOrBuilder(
        int index);
  }
  public static final class AList extends
      com.google.protobuf.GeneratedMessage
      implements AListOrBuilder {
    // Use AList.newBuilder() to construct.
    private AList(Builder builder) {
      super(builder);
    }
    private AList(boolean noInit) {}
    
    private static final AList defaultInstance;
    public static AList getDefaultInstance() {
      return defaultInstance;
    }
    
    public AList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return prototest.Ex.internal_static_prototest_AList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return prototest.Ex.internal_static_prototest_AList_fieldAccessorTable;
    }
    
    // repeated int32 age = 1;
    public static final int AGE_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> age_;
    public java.util.List<java.lang.Integer>
        getAgeList() {
      return age_;
    }
    public int getAgeCount() {
      return age_.size();
    }
    public int getAge(int index) {
      return age_.get(index);
    }
    
    // repeated .prototest.AThing things = 2;
    public static final int THINGS_FIELD_NUMBER = 2;
    private java.util.List<prototest.Ex.AThing> things_;
    public java.util.List<prototest.Ex.AThing> getThingsList() {
      return things_;
    }
    public java.util.List<? extends prototest.Ex.AThingOrBuilder> 
        getThingsOrBuilderList() {
      return things_;
    }
    public int getThingsCount() {
      return things_.size();
    }
    public prototest.Ex.AThing getThings(int index) {
      return things_.get(index);
    }
    public prototest.Ex.AThingOrBuilder getThingsOrBuilder(
        int index) {
      return things_.get(index);
    }
    
    private void initFields() {
      age_ = java.util.Collections.emptyList();;
      things_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < age_.size(); i++) {
        output.writeInt32(1, age_.get(i));
      }
      for (int i = 0; i < things_.size(); i++) {
        output.writeMessage(2, things_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < age_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(age_.get(i));
        }
        size += dataSize;
        size += 1 * getAgeList().size();
      }
      for (int i = 0; i < things_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, things_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static prototest.Ex.AList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static prototest.Ex.AList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static prototest.Ex.AList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static prototest.Ex.AList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static prototest.Ex.AList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static prototest.Ex.AList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static prototest.Ex.AList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static prototest.Ex.AList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static prototest.Ex.AList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static prototest.Ex.AList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(prototest.Ex.AList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements prototest.Ex.AListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return prototest.Ex.internal_static_prototest_AList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return prototest.Ex.internal_static_prototest_AList_fieldAccessorTable;
      }
      
      // Construct using prototest.Ex.AList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getThingsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        age_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (thingsBuilder_ == null) {
          things_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          thingsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return prototest.Ex.AList.getDescriptor();
      }
      
      public prototest.Ex.AList getDefaultInstanceForType() {
        return prototest.Ex.AList.getDefaultInstance();
      }
      
      public prototest.Ex.AList build() {
        prototest.Ex.AList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private prototest.Ex.AList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        prototest.Ex.AList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public prototest.Ex.AList buildPartial() {
        prototest.Ex.AList result = new prototest.Ex.AList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          age_ = java.util.Collections.unmodifiableList(age_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.age_ = age_;
        if (thingsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            things_ = java.util.Collections.unmodifiableList(things_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.things_ = things_;
        } else {
          result.things_ = thingsBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof prototest.Ex.AList) {
          return mergeFrom((prototest.Ex.AList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(prototest.Ex.AList other) {
        if (other == prototest.Ex.AList.getDefaultInstance()) return this;
        if (!other.age_.isEmpty()) {
          if (age_.isEmpty()) {
            age_ = other.age_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAgeIsMutable();
            age_.addAll(other.age_);
          }
          onChanged();
        }
        if (thingsBuilder_ == null) {
          if (!other.things_.isEmpty()) {
            if (things_.isEmpty()) {
              things_ = other.things_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureThingsIsMutable();
              things_.addAll(other.things_);
            }
            onChanged();
          }
        } else {
          if (!other.things_.isEmpty()) {
            if (thingsBuilder_.isEmpty()) {
              thingsBuilder_.dispose();
              thingsBuilder_ = null;
              things_ = other.things_;
              bitField0_ = (bitField0_ & ~0x00000002);
              thingsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getThingsFieldBuilder() : null;
            } else {
              thingsBuilder_.addAllMessages(other.things_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              ensureAgeIsMutable();
              age_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addAge(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 18: {
              prototest.Ex.AThing.Builder subBuilder = prototest.Ex.AThing.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addThings(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated int32 age = 1;
      private java.util.List<java.lang.Integer> age_ = java.util.Collections.emptyList();;
      private void ensureAgeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          age_ = new java.util.ArrayList<java.lang.Integer>(age_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<java.lang.Integer>
          getAgeList() {
        return java.util.Collections.unmodifiableList(age_);
      }
      public int getAgeCount() {
        return age_.size();
      }
      public int getAge(int index) {
        return age_.get(index);
      }
      public Builder setAge(
          int index, int value) {
        ensureAgeIsMutable();
        age_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addAge(int value) {
        ensureAgeIsMutable();
        age_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllAge(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureAgeIsMutable();
        super.addAll(values, age_);
        onChanged();
        return this;
      }
      public Builder clearAge() {
        age_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      
      // repeated .prototest.AThing things = 2;
      private java.util.List<prototest.Ex.AThing> things_ =
        java.util.Collections.emptyList();
      private void ensureThingsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          things_ = new java.util.ArrayList<prototest.Ex.AThing>(things_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          prototest.Ex.AThing, prototest.Ex.AThing.Builder, prototest.Ex.AThingOrBuilder> thingsBuilder_;
      
      public java.util.List<prototest.Ex.AThing> getThingsList() {
        if (thingsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(things_);
        } else {
          return thingsBuilder_.getMessageList();
        }
      }
      public int getThingsCount() {
        if (thingsBuilder_ == null) {
          return things_.size();
        } else {
          return thingsBuilder_.getCount();
        }
      }
      public prototest.Ex.AThing getThings(int index) {
        if (thingsBuilder_ == null) {
          return things_.get(index);
        } else {
          return thingsBuilder_.getMessage(index);
        }
      }
      public Builder setThings(
          int index, prototest.Ex.AThing value) {
        if (thingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureThingsIsMutable();
          things_.set(index, value);
          onChanged();
        } else {
          thingsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setThings(
          int index, prototest.Ex.AThing.Builder builderForValue) {
        if (thingsBuilder_ == null) {
          ensureThingsIsMutable();
          things_.set(index, builderForValue.build());
          onChanged();
        } else {
          thingsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addThings(prototest.Ex.AThing value) {
        if (thingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureThingsIsMutable();
          things_.add(value);
          onChanged();
        } else {
          thingsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addThings(
          int index, prototest.Ex.AThing value) {
        if (thingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureThingsIsMutable();
          things_.add(index, value);
          onChanged();
        } else {
          thingsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addThings(
          prototest.Ex.AThing.Builder builderForValue) {
        if (thingsBuilder_ == null) {
          ensureThingsIsMutable();
          things_.add(builderForValue.build());
          onChanged();
        } else {
          thingsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addThings(
          int index, prototest.Ex.AThing.Builder builderForValue) {
        if (thingsBuilder_ == null) {
          ensureThingsIsMutable();
          things_.add(index, builderForValue.build());
          onChanged();
        } else {
          thingsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllThings(
          java.lang.Iterable<? extends prototest.Ex.AThing> values) {
        if (thingsBuilder_ == null) {
          ensureThingsIsMutable();
          super.addAll(values, things_);
          onChanged();
        } else {
          thingsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearThings() {
        if (thingsBuilder_ == null) {
          things_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          thingsBuilder_.clear();
        }
        return this;
      }
      public Builder removeThings(int index) {
        if (thingsBuilder_ == null) {
          ensureThingsIsMutable();
          things_.remove(index);
          onChanged();
        } else {
          thingsBuilder_.remove(index);
        }
        return this;
      }
      public prototest.Ex.AThing.Builder getThingsBuilder(
          int index) {
        return getThingsFieldBuilder().getBuilder(index);
      }
      public prototest.Ex.AThingOrBuilder getThingsOrBuilder(
          int index) {
        if (thingsBuilder_ == null) {
          return things_.get(index);  } else {
          return thingsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends prototest.Ex.AThingOrBuilder> 
           getThingsOrBuilderList() {
        if (thingsBuilder_ != null) {
          return thingsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(things_);
        }
      }
      public prototest.Ex.AThing.Builder addThingsBuilder() {
        return getThingsFieldBuilder().addBuilder(
            prototest.Ex.AThing.getDefaultInstance());
      }
      public prototest.Ex.AThing.Builder addThingsBuilder(
          int index) {
        return getThingsFieldBuilder().addBuilder(
            index, prototest.Ex.AThing.getDefaultInstance());
      }
      public java.util.List<prototest.Ex.AThing.Builder> 
           getThingsBuilderList() {
        return getThingsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          prototest.Ex.AThing, prototest.Ex.AThing.Builder, prototest.Ex.AThingOrBuilder> 
          getThingsFieldBuilder() {
        if (thingsBuilder_ == null) {
          thingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              prototest.Ex.AThing, prototest.Ex.AThing.Builder, prototest.Ex.AThingOrBuilder>(
                  things_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          things_ = null;
        }
        return thingsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:prototest.AList)
    }
    
    static {
      defaultInstance = new AList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:prototest.AList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_prototest_Hobby_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_prototest_Hobby_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_prototest_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_prototest_Person_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_prototest_AddressBook_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_prototest_AddressBook_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_prototest_AThing_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_prototest_AThing_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_prototest_AList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_prototest_AList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010Ex.proto\022\tprototest\"\025\n\005Hobby\022\014\n\004name\030\001" +
      " \002(\t\"R\n\006Person\022\n\n\002id\030\001 \002(\005\022\014\n\004name\030\002 \002(\t" +
      "\022\r\n\005email\030\003 \001(\t\022\037\n\005hobby\030\004 \001(\0132\020.protote" +
      "st.Hobby\"0\n\013AddressBook\022!\n\006person\030\001 \003(\0132" +
      "\021.prototest.Person\",\n\006AThing\022\014\n\004toys\030\001 \003" +
      "(\t\022\024\n\014luckynumbers\030\002 \003(\005\"7\n\005AList\022\013\n\003age" +
      "\030\001 \003(\005\022!\n\006things\030\002 \003(\0132\021.prototest.AThin" +
      "g"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_prototest_Hobby_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_prototest_Hobby_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_prototest_Hobby_descriptor,
              new java.lang.String[] { "Name", },
              prototest.Ex.Hobby.class,
              prototest.Ex.Hobby.Builder.class);
          internal_static_prototest_Person_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_prototest_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_prototest_Person_descriptor,
              new java.lang.String[] { "Id", "Name", "Email", "Hobby", },
              prototest.Ex.Person.class,
              prototest.Ex.Person.Builder.class);
          internal_static_prototest_AddressBook_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_prototest_AddressBook_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_prototest_AddressBook_descriptor,
              new java.lang.String[] { "Person", },
              prototest.Ex.AddressBook.class,
              prototest.Ex.AddressBook.Builder.class);
          internal_static_prototest_AThing_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_prototest_AThing_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_prototest_AThing_descriptor,
              new java.lang.String[] { "Toys", "Luckynumbers", },
              prototest.Ex.AThing.class,
              prototest.Ex.AThing.Builder.class);
          internal_static_prototest_AList_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_prototest_AList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_prototest_AList_descriptor,
              new java.lang.String[] { "Age", "Things", },
              prototest.Ex.AList.class,
              prototest.Ex.AList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
